services:
  web:
    build:
      context: .
      dockerfile: production.Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: "False"
      PORT: "5000"
      DATABASE_URL: "sqlite:////app/class_app.db"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      USE_AWS_SECRETS_MANAGER: "true"
      AWS_REGION: "us-east-1"
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_SECRETS_NAME: "ZTF_Prod_Secrets"
      OAUTHLIB_INSECURE_TRANSPORT: "0"
      AUTHLIB_INSECURE_TRANSPORT: "0"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
